public enum EventID
{
    NONE = 0,
    ON_KNIFE_LAUNCH,
    ON_KNIFE_HIT_LOG_TRUE,
    ON_KNIFE_HIT_LOG_FALSE,
    ON_GAME_END,
    ON_GAME_START,
    ON_KNIVES_TAKEN_DOWN,
    ON_HIT_POWERUP,
    ON_KNIFE_HIT,
    ON_BUTTON_HIT,
    ON_PLAYER_DEAD,
}