public enum EventID
{
    NONE = 0,
    ON_FRAMEVIEW_HAS_TOUCHED,
    IN_GAME_STATE_PICKING,
    ON_KNIFE_SUCCESS,
    ON_KNIFE_FALL,
    ON_PLAYER_TOUCH_BUTTON,
    ON_PLAYER_TIMER_END,
    ON_PLAYER_WIN,
    ON_GAME_START,
    ON_HIT_POWERUP,
}